### PR TITLE
Install deps automatically when installing rss2email

### PR DESCRIPTION
**Pull request by untitaker**

### CODE REVIEW

**Comment by wking** [comment]
install_requires is a setuptools extension [1].  Until Python's stdlib
gets the ability to do this sort of thing, I'd rather leave it to the
system packager to avoid requiring setuptools.  Until then, the notes
in the manual-install section should have you covered [2], although
I'm ok with adding a requirements.txt if that's more convenient.

[1]: https://packaging.python.org/en/latest/requirements/#install-requires
[2]: https://github.com/wking/rss2email#requirements

**Comment by untitaker** [comment]
I'd consider that extension safe to use, as literally every piece of software I've ever seen depends on it.

System packagers manage the dependencies themselves anyway, and distutils ignores unknown options.

**Comment by wking** [comment]
On Tue, Sep 15, 2015 at 04:41:57PM -0700, Markus Unterwaditzer wrote:
> I'd consider that extension safe to use, as literally every piece of
> software I've ever seen depends on it.

I've had trouble in the past with packages pulling in setuptools,
because it's hard to install a system setuptools for an unstable
Python on Gentoo without rebuilding your whole Python stack ;).

> … and distutils ignores unknown options.

Ah, that's good to know.  Can you read over the submitting guidelines
[1], and if it seems ok to you, add your Signed-off-by to this commit?

[1]: https://github.com/wking/rss2email/blob/master/CONTRIBUTING.md

**Comment by wking** [comment]
On Tue, Sep 15, 2015 at 08:19:27PM -0700, W. Trevor King wrote:
> Tue, Sep 15, 2015 at 04:41:57PM -0700, Markus Unterwaditzer:
> > … and distutils ignores unknown options.
> 
> Ah, that's good to know…

Hmm, I just tested this locally, and got:

  $ python setup.py --help
  /usr/lib64/python3.4/distutils/dist.py:260: UserWarning: Unknown distribution option: 'install_requires'
    warnings.warn(msg)
  …

So “warns but continues anyway” may be more accurate than “ignores”
;).  It still may be reasonable to make pip installs easier,
especially since html2text seems to have had a new release [1], so we
no longer need to run an unreleased dev snapshot for rss2email.

[1]: https://pypi.python.org/pypi/html2text

**Comment by untitaker** [comment]
For me that's the same thing, regardless of what pip outputs.

Before I go through the trouble of figuring out how to sign commits I'd like to
know for sure if you accept this patch.

**Comment by wking** [comment]
On Wed, Sep 16, 2015 at 01:07:58PM -0700, Markus Unterwaditzer wrote:
> For me that's the same thing, regardless of what pip outputs.

Pip apparently always uses setuptools [1], so you'll only see that
warning if you install directly with distutils (like I do ;).  I'm ok
with the warning there to make life easier for pip users, so I'll
merge this once it gets a sign-off.

> Before I go through the trouble of figuring out how to sign commits…

I'm not sure how to do it through the GitHub UI (I guess you could
always open a new pull request?), but I'm happy to talk you through it
if you want to do it with command-line Git (notes on rerolling here
[2]).

[1]: https://packaging.python.org/en/latest/requirements/#install-requires
[2]: http://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

**Comment by untitaker** [comment]
I know how to check out branches and rewrite history, I just need to figure out
how to do signing.

Give me a minute.

Also, would you consider something like this:

    try:
        from setuptools import setup
    except ImportError:
        from distutils.core import setup

**Comment by untitaker** [comment]
I don't really get why `Signed-Off-By` and actually signing are two different things but the commit now has both.

**Comment by wking** [comment]
On Wed, Sep 16, 2015 at 01:29:12PM -0700, Markus Unterwaditzer wrote:
> I don't really get why `Signed-Off-By` and actually signing are two
> different things but the commit now has both.

All I need was the former.  Signed-off-by says that you've read the
DCO and assert that it applies to the commit you're submitting
(e.g. you haven't stolen the commit from some proprietary codebase ;).

*Signing* the commit (which I don't need, but will happily accept)
asserts in a verifiable way that someone with the private key to
FAAC788C (probably you ;) created the commit object itself.

Anyhow, merged now, and thanks :).

**Comment by wking** [comment]
On Wed, Sep 16, 2015 at 01:23:04PM -0700, Markus Unterwaditzer wrote:
> Also, would you consider something like this:
> 
>     try:
>         from setuptools import setup
>     except ImportError:
>         from distutils.core import setup

To what end?  It sounds like pip is always going to be using
setuptools anyway.

**Comment by untitaker** [comment]
Right but it means that if setuptools is installed, using `python setup.py
install` will prefer it and therefore also automatically install dependencies.

**Comment by wking** [comment]
On Wed, Sep 16, 2015 at 01:45:58PM -0700, Markus Unterwaditzer wrote:
> Right but it means that if setuptools is installed, using `python
> setup.py install` will prefer it and therefore also automatically
> install dependencies.

If you have the directory locally and want to install with setuptools,
just run ‘pip install .’

**Pull request merged**
