### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by monperrus**

### CODE REVIEW

**Comment by sciunto** [comment]
@wking This one looks good to me.

**Comment by RalphCorderoy** [comment]
The patch assumes the value of XDG_DATA_HOME;  see r2e(1) for more.

**Comment by leezu** [comment]
Merged in https://github.com/leezu/rss2email/tree/leezu and hopefully to be included in the rss2mail fork having admin access to the pypi package: https://github.com/rss2email/rss2email/pull/13

**Comment by Ekleog** [comment]
@monperrus This has been merged in https://github.com/rss2email/rss2email (following maintainership changes), care to close this PR? :)

**Comment by monperrus** [comment]
Excellent, thanks. Still heavy using rss2email.

**Pull request closed without merging**
