### PR TITLE
Implemented image attachments

### PR DESCRIPTION
**Pull request by bdc34**
Modifying the html to use cid's to the attachements
Adding note to README that BeautifulSoup4 is required
Changing r2e to use python3

Signed-off-by: Brian Caruso briancaruso@gmail.com

### CODE REVIEW

**Comment by Ekleog** [comment]
@bdc34 The `rss2email` repository has moved to https://github.com/rss2email/rss2email following maintainership changes. This PR appears WIP and not ready to be merged for now, plus it apparently points to a feature branch of this repo, and it looks like I can't just create a PR from your PR to there myself (I guess due to the two not being forks-according-to-github). Would you mind sending your PR over there if you think it's useful?

**Comment by bdc34** [comment]
Léo

Sorry, I do not think it will be useful anymore. It would be better to start this from scratch.

Thanks for your work,
Brian Caruso
Repository Developer
Cornell University Library
t 607-255-1790

________________________________________

**Comment by Ekleog** [comment]
OK, thank you for your feedback! :)

**Comment by bdc34** [comment]
Closed due to lack of interest.

**Pull request closed without merging**
