### PR TITLE
Fix README

### PR DESCRIPTION
**Pull request by Kh4l3tH**
Fix config entry for smtp use

### CODE REVIEW

**Comment by leezu** [comment]
Merged in https://github.com/leezu/rss2email/tree/leezu and hopefully to be included in the rss2mail fork having admin access to the pypi package: https://github.com/rss2email/rss2email/pull/13

**Comment by Ekleog** [comment]
@Kh4l3tH This has been merged in https://github.com/rss2email/rss2email (following maintainership changes); care to close this PR? :)

**Comment by Kh4l3tH** [comment]
absolutly not
mind telling me where i would have seen this myself? :>

**Comment by Ekleog** [comment]
You could have noticed when the PR pointed to by @leezu's comment has been merged, but I don't think it'd have been reasonable to expect that from you -- migrating from one repo to another one without having the rights on the first repo is not necessarily easy, sorry :)

**Pull request closed without merging**
